name: myenv
channels:
  - defaults
  - nvidia
  - pytorch
dependencies:
  - aiodns=3.5.0=py39haa95532_0
  - aiohappyeyeballs=2.6.1=py39haa95532_0
  - aiohttp=3.12.15=py39h02ab6af_0
  - aiosignal=1.4.0=py39haa95532_0
  - arrow-cpp=21.0.0=h0399227_0
  - async-timeout=5.0.1=py39haa95532_0
  - attrs=25.4.0=py39haa95532_1
  - aws-c-auth=0.9.0=h02ab6af_2
  - aws-c-cal=0.9.2=h02ab6af_1
  - aws-c-common=0.12.4=h02ab6af_0
  - aws-c-compression=0.3.1=h02ab6af_2
  - aws-c-event-stream=0.5.6=h02ab6af_0
  - aws-c-http=0.10.4=h02ab6af_0
  - aws-c-io=0.21.4=h02ab6af_0
  - aws-c-mqtt=0.13.3=h02ab6af_0
  - aws-c-s3=0.8.7=h02ab6af_0
  - aws-c-sdkutils=0.2.4=h02ab6af_1
  - aws-checksums=0.2.7=h02ab6af_1
  - aws-crt-cpp=0.34.0=h885b0b7_0
  - aws-sdk-cpp=1.11.638=hf0af688_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py39hc99e966_0
  - brotlicffi=1.0.9.2=py39h885b0b7_2
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h731ff69_0
  - ca-certificates=2025.11.4=haa95532_0
  - cairo=1.18.4=he9e932c_0
  - certifi=2025.10.5=py39haa95532_0
  - cffi=2.0.0=py39h02ab6af_0
  - charset-normalizer=3.4.4=py39haa95532_0
  - colorama=0.4.6=py39haa95532_0
  - contourpy=1.2.1=py39h214f63a_1
  - cuda-cccl=12.9.27=0
  - cuda-cccl_win-64=12.9.27=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-opencl-dev=12.9.19=0
  - cuda-profiler-api=12.9.79=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - cycler=0.11.0=pyhd3eb1b0_0
  - datasets=3.3.2=py39haa95532_0
  - dill=0.3.8=py39haa95532_0
  - expat=2.7.3=h9214b88_0
  - filelock=3.17.0=py39haa95532_0
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.60.1=py39h02ab6af_0
  - freetype=2.13.3=h0620614_0
  - frozenlist=1.8.0=py39h885b0b7_0
  - fsspec=2024.12.0=py39haa95532_0
  - gflags=2.2.2=hd77b12b_1
  - giflib=5.2.2=h7edc060_0
  - glog=0.5.0=hd77b12b_1
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py39h827c3e9_0
  - graphite2=1.3.14=hd77b12b_1
  - harfbuzz=10.2.0=he2f9f60_1
  - hf-xet=1.1.8=py39h79d111c_0
  - huggingface_hub=0.34.4=py39haa95532_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.11=py39haa95532_0
  - importlib_resources=6.5.2=py39haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jinja2=3.1.6=py39haa95532_0
  - joblib=1.5.2=py39haa95532_0
  - jpeg=9f=ha349fce_0
  - khronos-opencl-icd-loader=2024.05.08=h8cc25b3_0
  - kiwisolver=1.4.4=py39hd77b12b_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libbrotlicommon=1.0.9=h827c3e9_9
  - libbrotlidec=1.0.9=h827c3e9_9
  - libbrotlienc=1.0.9=h827c3e9_9
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.3.10.19=0
  - libcurand-dev=10.3.10.19=0
  - libcurl=8.16.0=h97e0424_0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.4=hfaec014_0
  - libgrpc=1.71.0=hf4237ab_0
  - libiconv=1.16=h2bbff1b_3
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libkrb5=1.21.3=h885b0b7_4
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libpng=1.6.50=h46444df_0
  - libpq=17.6=h652a1e2_0
  - libprotobuf=5.29.3=h65a231f_1
  - libre2-11=2024.07.02=h5da7b33_0
  - libssh2=1.11.1=h2addb87_0
  - libthrift=0.15.0=ha2884a9_4
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py39h827c3e9_0
  - matplotlib=3.9.2=py39haa95532_1
  - matplotlib-base=3.9.2=py39he19b0ae_1
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py39h827c3e9_2
  - mkl_fft=1.3.11=py39h827c3e9_0
  - mkl_random=1.2.8=py39hc64d2fc_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py39haa95532_0
  - multidict=6.7.0=py39h02ab6af_0
  - multiprocess=0.70.15=py39haa95532_0
  - mysql-common=9.3.0=hf582a5b_3
  - mysql-libs=9.3.0=hc0ebf12_3
  - networkx=3.2.1=py39haa95532_0
  - numexpr=2.10.1=py39h4cd664f_0
  - numpy=1.26.4=py39h055cbcc_0
  - numpy-base=1.26.4=py39h65a83cf_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.18=h543e019_0
  - orc=2.2.0=hf43e1a1_0
  - packaging=25.0=py39haa95532_1
  - pandas=2.3.3=py39ha5e6156_0
  - pcre2=10.46=h5740b90_0
  - pillow=11.1.0=py39h096bfcc_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h4043f72_0
  - propcache=0.3.1=py39h827c3e9_0
  - protobuf=5.29.3=py39h5da7b33_0
  - pyarrow=21.0.0=py39ha5e6156_0
  - pybind11-abi=5=hd3eb1b0_0
  - pycares=4.10.0=py39he29e43d_0
  - pycparser=2.23=py39haa95532_0
  - pyparsing=3.2.0=py39haa95532_0
  - pyqt=6.9.1=py39h12ec796_0
  - pyqt6-sip=13.10.2=py39h630b2a1_0
  - pysocks=1.7.1=py39haa95532_1
  - python=3.9.25=h716150d_1
  - python-dateutil=2.9.0post0=py39haa95532_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py39h827c3e9_0
  - pytorch=2.5.1=py3.9_cuda12.1_cudnn9_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=py39haa95532_0
  - pyyaml=6.0.2=py39h827c3e9_0
  - qtbase=6.9.2=h06bae2a_4
  - qtdeclarative=6.9.2=h88b4c33_1
  - qtsvg=6.9.2=h30ace32_1
  - qttools=6.9.2=h7e7b719_1
  - qtwebchannel=6.9.2=heb02b0b_1
  - qtwebsockets=6.9.2=heb02b0b_1
  - re2=2024.07.02=h214f63a_0
  - regex=2025.9.1=py39h02ab6af_0
  - requests=2.32.5=py39haa95532_0
  - safetensors=0.5.3=py39haa69e8e_0
  - scikit-learn=1.5.1=py39hc64d2fc_0
  - scipy=1.13.1=py39h8640f81_1
  - setuptools=80.9.0=py39haa95532_0
  - sip=6.12.0=py39h706e071_0
  - six=1.17.0=py39haa95532_0
  - snappy=1.2.1=hcdb6601_0
  - sqlite=3.50.2=hda9a48d_1
  - tbb=2021.8.0=h59b6b97_0
  - threadpoolctl=3.5.0=py39h9909e9c_0
  - tk=8.6.15=hf199647_0
  - tokenizers=0.21.0=py39h5bc5163_0
  - tomli=2.2.1=py39haa95532_0
  - tornado=6.5.1=py39h827c3e9_0
  - tqdm=4.67.1=py39h9909e9c_0
  - transformers=4.49.0=py39haa95532_0
  - typing-extensions=4.15.0=py39haa95532_0
  - typing_extensions=4.15.0=py39haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py39haa95532_0
  - utf8proc=2.6.1=h2bbff1b_1
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py39haa95532_0
  - win_inet_pton=1.1.0=py39haa95532_1
  - winloop=0.2.2=py39h913537a_0
  - xxhash=0.8.0=h2bbff1b_3
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - yarl=1.18.0=py39h827c3e9_0
  - zipp=3.21.0=py39haa95532_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - accelerate==1.10.1
      - einops==0.8.1
      - psutil==7.1.3
      - sympy==1.13.1
      - torchaudio==2.5.1
      - torchvision==0.20.1
prefix: C:\ProgramData\miniconda3\envs\myenv
